# Generated by Django 5.0.9 on 2024-09-13 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='author',
            field=models.ForeignKey(default='unknown author', on_delete=django.db.models.deletion.SET_DEFAULT, to='audioapp.author'),
        ),
    ]
