# Generated by Django 5.0.9 on 2024-09-13 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0002_author_alter_track_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
