# Generated by Django 5.0.9 on 2024-09-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0003_track_track_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='track_file',
            field=models.FileField(blank=True, null=True, upload_to='tracks/'),
        ),
    ]
