# Generated by Django 5.0.9 on 2024-09-13 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0004_alter_track_track_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='audioapp.author'),
        ),
        migrations.AlterField(
            model_name='track',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
