# Generated by Django 5.0.9 on 2024-09-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0005_alter_track_author_alter_track_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
