# Generated by Django 5.0.9 on 2024-09-15 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0006_alter_author_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('author', 'title')},
        ),
    ]
